Updated pre-commit hook

diff --git a/.git_hooks/pre-commit b/.git_hooks/pre-commit
--- a/.git_hooks/pre-commit
+++ b/.git_hooks/pre-commit
@@ -1,11 +1,13 @@
 #!/bin/sh
 
 # Get a list of the staged files
-FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+STAGED_RUBY_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | grep ".rb")
 
-# If the files list is empty exit
-[ -z "$FILES" ] && exit 0
+# If ruby_files string is non-zero
+if [ ! -z $STAGED_RUBY_FILES ]
+then
+  echo "[Pre commit hook] Running standardrb linting"
 
-echo "[Pre commit hook] Running standardrb linting"
-
-docker compose run --rm --no-deps -T web standardrb $FILES
+  # If standardrb returns a non 0 response, exit
+  docker compose run --rm --no-deps -T web standardrb $STAGED_RUBY_FILES || exit 1
+fi
